using System.Collections.Generic;

namespace NoREroMod.Systems.Spawn;

internal static partial class SpawnAuthoringLoc
{
    private static void ApplyFr(Dictionary<string, string> d)
    {
        ApplyEastAsian(d,
            coordsTitle: "Placement",
            point: "Point",
            pack: "Pack",
            pending: "En attente",
            clipboard: "Copié",
            selected: "Sélection",
            line: "Ligne",
            hotkeys: "LMB = Point · LMB-glisser = cadre · Ctrl+C/X/V/D · flèches · Shift+flèches · E H T R G N M C F B V U · Home · Space · RMB reload · F12 · F1 · Q",
            dragging: "Déplacement…",
            clickReady: "Point de spawn prêt",
            clickUpdated: "Coordonnées mises à jour",
            marker: "SPAWN",
            copied: "Objet copié",
            cut: "Coupé",
            pasted: "Collé",
            duplicated: "Dupliqué",
            deleted: "Supprimé",
            shotOk: "Capture enregistrée",
            shotFail: "Échec de la capture",
            btnShot: "Capture [F12]",
            btnHelp: "Aide [F1]",
            enemies: "Ennemis [E]",
            enemiesOpen: "Ennemis ▲ [E]",
            hostage: "Otage [H]",
            hostageOpen: "Otage ▲ [H]",
            hostageTitle: "Otages & OtherScenes",
            helpHostage: "Otages, puis animations Spine (Look_Dorei, gob_look, …). |faction= est hérité par le combattant après le sauvetage. Random écrit RANDOM_HOSTAGE.",
            trap: "Piège [T]",
            trapOpen: "Piège ▲ [T]",
            lethal: "Létal [R]",
            lethalOpen: "Létal ▲ [R]",
            decor: "Décor [N]",
            decorOpen: "Décor ▲ [N]",
            gold: "Or [G]",
            goldOpen: "Or ▲ [G]",
            goldTitle: "Tas d’or",
            helpGold: "Place un tas d’or. Montants fixes ou plages. Random écrit RANDOM,chance,X,Y,gold=…",
            helpGoldOpt: "Random = RANDOM,chance. Statique = GOLD,X,Y,amount,1.",
            etTitle: "Ancres EventTrap",
            helpEt: "Écrit EVENTTRAP,folder,X,Y plus count/dist/sides/faction/max/r/delay optionnels. Champs vides = config.json du pack. F11 affiche un gizmo (invisible en jeu).",
            helpEtGizmo: "Ancre d’embuscade/renfort réservée à l’éditeur. Invisible en jeu. Glisse ou saisis XY, puis Utiliser la position / Enregistrer.",
            helpEtOpt: "Vide = défauts du pack. Distances depuis le joueur au knockdown, pas depuis l’ancre. Faction appliquée aux ennemis d’embuscade. Sides : pack / both / right-only.",
            ecNone: "Aucun",
            ecAttach: "Événement p=",
            helpEc: "Place un PNJ de dialogue : TouzokuNormal|ec_event=<id>. Broker / FSP bandits = toujours TouzokuNormal. Clique Point, puis Placer. LMB sur le PNJ pour éditer.",
            helpEcOpt: "Random = chance d’apparition du PNJ (RANDOM,chance). Événement p= = |ec_chance=. Le PNJ spawn toujours ; 1 = dialogue toujours attaché. Faction par défaut = rencontre d’événement.",
            helpPrevEc: "Aperçu du prefab PNJ lié. Glisse depuis l’aperçu ou la liste vers la carte pour placer et enregistrer.",
            count: "Nombre",
            dist: "Dist",
            max: "Max",
            zone: "Zone",
            delay: "Délai",
            sidesPack: "Côtés : pack",
            sidesBoth: "Côtés : les deux",
            sidesRight: "Côtés : droite",
            decorTitle: "Décors",
            spine: "— Animations Spine —",
            helpDecor: "Caisses, tonneaux, cadavres, props. Les looks Spine sont sous Otages & OtherScenes. (?) = pas encore en cache.",
            fav: "Favoris ★ [B]",
            favOpen: "Favoris ▲ [B]",
            btnDel: "Suppr. [Del]",
            btnUndo: "Annuler  [Ctrl+Z]",
            btnCopy: "Copier [Ctrl+C]",
            btnCut: "Couper [Ctrl+X]",
            btnPaste: "Coller [Ctrl+V]",
            viewOff: "Vue [V]",
            viewOn: "Vue ON [V]",
            confirm: "Placer  [Space]",
            confirmFull: "Placer et sauver  [Space]",
            addFav: "★ Ajouter aux favoris [Ctrl+B]",
            favDel: "Suppr.",
            btnSave: "Sauver  [Ctrl+S]",
            btnSaved: "✓ Sauvé",
            closeEdit: "Fermer",
            usePos: "Prendre position [U]",
            reset: "Reset",
            barUndo: "Annuler",
            barSave: "Sauver",
            barFlip: "Flip [F]",
            barFlipOn: "Flip ON [F]",
            barCopy: "Copier",
            barCut: "Couper",
            barPaste: "Coller",
            barDelete: "Suppr.",
            barPlace: "Placer [␣]",
            trapsTitle: "Pièges",
            lethalTitle: "Pièges létaux",
            helpTraps: "Choisis une clé, flip/rot/sort, clique Point, Place. LMB sur un piège posé = éditer/supprimer. (?) = pas en cache.",
            helpLethal: "Pièges létaux HellGate (gore). Flip/sort seulement (pas de rotation). Gore Content requis.",
            flipOn: "Vers la gauche [F]",
            flipOff: "Vers la droite [F]",
            ready: "Prêt",
            enemiesTitle: "Ennemis",
            favTitle: "Favoris",
            favEmpty: "Vide — choisis une clé, puis ★.",
            favAdd: "★ Ajouter l’actuel",
            factionTitle: "Faction",
            elite: "Élite",
            flip: "Flip gauche",
            rot: "Rotation",
            degrees: "Degrés",
            apply: "OK",
            sort: "Sort",
            random: "Chance aléatoire",
            options: "Options",
            preview: "Aperçu",
            pickEnemy: "Choisis un ennemi",
            pickTrap: "Choisis un piège",
            noPrefab: "Pas de prefab",
            noMesh: "Pas de mesh",
            unavailable: "Indisponible",
            na: "[N/D]",
            enemyNa: "Cet ennemi n’est pas disponible pour l’édition.",
            helpTitle: "Aide",
            guideTitle: "Contrôles",
            cam: "Caméra / déplacement",
            camBody: "WASD — déplacer la caméra\nMaintenir MMB et glisser — déplacer la caméra à la souris\nMolette — zoom (active la Vue)\nV — Vue / Default\nHome — caméra sur le joueur (Vue conservée, zoom réinitialisé)",
            mouse: "Souris",
            mouseBody: "LMB sur le sol vide — poser le Point\nLMB-glisser sur le sol — sélectionner un cadre\nLMB sur un sprite — sélectionner / éditer (précis ; Alt = plus large)\nMaintenir LMB sur un objet — le déplacer\nFlèches — décaler la sélection (Shift+flèches ×5)\nGlisser l’aperçu ou la liste vers la carte — placer et enregistrer\nRMB — enregistrer le pack et recharger la scène",
            catalogs: "Catalogues",
            catalogsBody: "E — Ennemis\nH — Otages\nT — Pièges\nR — Pièges létaux\nG — Or\nN — Décor\nM — EventTrap\nC — EventCore\nB — Favoris\nF — Retournement\nSpace / Enter — Placer\nU — Utiliser la position\nQ — fermer les panneaux (et cette aide)",
            editClip: "Édition et presse-papiers",
            editBody: "Ctrl+C — copier\nCtrl+X — couper\nCtrl+V — coller au Point\nCtrl+D — dupliquer\nCtrl+Z — annuler\nCtrl+S — enregistrer l’édition\nCtrl+B — ajouter aux favoris\nDel — supprimer (un cadre supprime tout dedans)\nF12 — capture\nF1 — cette aide\nEsc — fermer l’aide, puis le cadre, puis l’édition, puis la sélection",
            footer: "Survole ? sur un panneau pour plus d’astuces.",
            helpCoords: "LMB sur le sol vide = Point. LMB-glisser au sol = cadre (Ctrl+C/X, Ctrl+V au Point). LMB sur un sprite = sélection/édition (Alt = plus large). Maintenir LMB = déplacer. MMB / WASD = déplacer la caméra. Molette = zoom. Flèches (Shift+flèches ×5). Home = caméra joueur. F1 aide. F12 capture. − replie ce panneau.",
            helpFaction: "Faction écrite dans la ligne du pack. Emblème = icône HellGate. < > pour cycler. Noms d’affichage ; le pack garde le jeton technique.",
            helpOpt: "Élite = ForceElite. Flip = −X. Random = RANDOM,chance.",
            helpTrapOpt: "Flip = horizontal. Rotation : +30° [R] ou degrés + OK. Sort = sort±N (SortingOrder, pas near/far).",
            helpHostOpt: "Flip = horizontal. Sort = sort±N. Random écrit RANDOM_HOSTAGE. Otages et OtherScenes ne tournent pas.",
            helpLetOpt: "Flip = horizontal. Sort = sort±N. Les pièges létaux ne tournent pas.",
            helpPrev: "Vignette de l’ennemi en attente. Glisse aperçu/liste vers la carte pour placer et sauver.",
            helpPrevTrap: "Vignette du modèle de piège. Glisse pour placer et sauver. (?) = visite d’abord une carte qui contient ce piège.",
            dragPlace: "Glisse aperçu ou liste vers la carte",
            dragRelease: "Relâche pour placer et sauver",
            facNone: "Aucune",
            facBandits: "Bandits",
            facInq: "Bandits (Inquisition)",
            facMafia: "Bandits (Mafia)",
            facDemons: "Bandits (Démons)",
            facChurch: "Église",
            facDemons2: "Démons",
            facMafia2: "Mafia",
            facUndead: "Morts-vivants",
            facMonsters: "Monstres",
            facWitch: "Sorcière",
            facEvent: "Rencontre d’événement",
            editTitle: "Sélection",
            editKey: "Clé",
            editFaction: "Faction",
            editRandom: "Spawn aléatoire",
            editChance: "Chance",
            editVanilla: "Pas lié à un pack — édition indisponible.",
            panelsClosed: "Panneaux fermés [Q]",
            pickKey: "Choisis d’abord une clé.",
            selectEnemy: "Sélectionne d’abord un ennemi (survol + LMB).",
            editDisabled: "Pas lié à un pack — édition indisponible.",
            pasteNeed: "Clique un point sur la carte, puis Ctrl+V.",
            camHome: "Caméra → joueur",
            camHomeFail: "Joueur introuvable.",
            badSort: "Sort invalide.",
            badRot: "Degrés de rotation invalides.",
            done: "Terminé.",
            noLink: "Pas lié à un pack.",
            noLinkXy: "Pas lié à un pack — XY non écrits.",
            keyReq: "Clé requise.",
            badXy: "X/Y invalides (format 12.34).",
            goldReq: "Montant d’or requis.",
            delFail: "Échec de la suppression.",
            cutFail: "Échec de la coupe.",
            copyFail: "Échec de la copie.",
            pasteFail: "Échec du collage.",
            undoEmpty: "Rien à annuler.",
            savedXy: "XY enregistrés → pack",
            cutCount: "Coupé × {0}  → Ctrl+V au Point",
            deletedCount: "Supprimé × {0}  (Ctrl+Z annuler)",
            copyDelFail: "{0}  (échec suppression : {1})",
            savedKeyAt: "Sauvé {0} @ {1},{2} → ligne {3}",
            selectPack: "Sélectionne d’abord un spawn HellGate (édition/suppression interdites pour le vanilla).",
            deletedLine: "Ligne de pack {0}{1} supprimée  (Ctrl+Z annuler)",
            regionEmpty: "Cadre vide.",
            delRegionFail: "Échec de suppression du cadre.",
            needPoint: "Clique d’abord un point sur la carte (LMB).",
            noEnemy: "Aucun ennemi confirmé.",
            noTrap: "Aucun piège confirmé.",
            noGold: "Pas de montant d’or.",
            noFolder: "Pas de dossier EventTrap.",
            camMissing: "Caméra introuvable.",
            camSize: "Impossible de lire la taille de base de la caméra.",
            overviewOn: "Vue ON — WASD / MMB-glisser déplacent la caméra, molette zoom. V = Default.",
            viewDefault: "Vue Default (standard).");
    }

    private static void ApplyDe(Dictionary<string, string> d)
    {
        ApplyEastAsian(d,
            coordsTitle: "Platzierung",
            point: "Punkt",
            pack: "Pack",
            pending: "Ausgewählt",
            clipboard: "Kopiert",
            selected: "Markiert",
            line: "Zeile",
            hotkeys: "LMB = Punkt · LMB-ziehen = Rahmen · Ctrl+C/X/V/D · Pfeile · Shift+Pfeile · E H T R G N M C F B V U · Home · Space · RMB reload · F12 · F1 · Q",
            dragging: "Ziehen…",
            clickReady: "Spawn-Punkt bereit",
            clickUpdated: "Koordinaten aktualisiert",
            marker: "SPAWN",
            copied: "Objekt kopiert",
            cut: "Ausgeschnitten",
            pasted: "Eingefügt",
            duplicated: "Dupliziert",
            deleted: "Gelöscht",
            shotOk: "Screenshot gespeichert",
            shotFail: "Screenshot fehlgeschlagen",
            btnShot: "Bild [F12]",
            btnHelp: "Hilfe [F1]",
            enemies: "Gegner [E]",
            enemiesOpen: "Gegner ▲ [E]",
            hostage: "Geisel [H]",
            hostageOpen: "Geisel ▲ [H]",
            hostageTitle: "Geiseln & OtherScenes",
            helpHostage: "Geiseln, dann Spine-Looks (Look_Dorei, gob_look, …). |faction= geht nach der Rettung auf den Kämpfer über. Random schreibt RANDOM_HOSTAGE.",
            trap: "Falle [T]",
            trapOpen: "Falle ▲ [T]",
            lethal: "Tödlich [R]",
            lethalOpen: "Tödlich ▲ [R]",
            decor: "Deko [N]",
            decorOpen: "Deko ▲ [N]",
            gold: "Gold [G]",
            goldOpen: "Gold ▲ [G]",
            goldTitle: "Goldhaufen",
            helpGold: "Goldhaufen platzieren. Fix oder Bereich. Random schreibt RANDOM,chance,X,Y,gold=…",
            helpGoldOpt: "Random = RANDOM,chance. Statisch = GOLD,X,Y,amount,1.",
            etTitle: "EventTrap-Anker",
            helpEt: "Schreibt EVENTTRAP,folder,X,Y plus optionale count/dist/sides/faction/max/r/delay. Leere Felder = pack config.json. F11 zeigt ein Gizmo (im Spiel unsichtbar).",
            helpEtGizmo: "Nur-Editor-Anker für Hinterhalt/Verstärkung. Im Spiel unsichtbar. Ziehe oder tippe XY, dann Position nutzen / Speichern.",
            helpEtOpt: "Leer = Pack-Defaults. Distanz vom Spieler beim Knockdown, nicht vom Anker. Fraktion gilt für Hinterhalt-Gegner. Sides: pack / both / right-only.",
            ecNone: "Keine",
            ecAttach: "Event p=",
            helpEc: "Dialog-NPC: TouzokuNormal|ec_event=<id>. Broker / FSP bandits immer TouzokuNormal. Punkt klicken, dann Platzieren. LMB auf den NPC zum Bearbeiten.",
            helpEcOpt: "Random = NPC-Spawnchance (RANDOM,chance). Event p= = |ec_chance=. NPC spawnt immer; 1 = Dialog immer. Fraktion Standard = Event-Begegnung.",
            helpPrevEc: "Vorschau des gebundenen NPC-Prefabs. Aus Vorschau/Liste auf die Karte ziehen = platzieren & speichern.",
            count: "Anzahl",
            dist: "Dist",
            max: "Max",
            zone: "Zone",
            delay: "Delay",
            sidesPack: "Seiten: Pack",
            sidesBoth: "Seiten: beide",
            sidesRight: "Seiten: rechts",
            decorTitle: "Dekoration",
            spine: "— Spine-Animationen —",
            helpDecor: "Kisten, Fässer, Leichen, Props. Spine-Looks unter Geiseln & OtherScenes. (?) = noch nicht im Cache.",
            fav: "Favoriten ★ [B]",
            favOpen: "Favoriten ▲ [B]",
            btnDel: "Löschen [Del]",
            btnUndo: "Undo  [Ctrl+Z]",
            btnCopy: "Kopieren [Ctrl+C]",
            btnCut: "Ausschneiden [Ctrl+X]",
            btnPaste: "Einfügen [Ctrl+V]",
            viewOff: "Übersicht [V]",
            viewOn: "Übersicht AN [V]",
            confirm: "Platzieren  [Space]",
            confirmFull: "Platzieren & speichern  [Space]",
            addFav: "★ Zu Favoriten [Ctrl+B]",
            favDel: "Entf.",
            btnSave: "Speichern  [Ctrl+S]",
            btnSaved: "✓ Gespeichert",
            closeEdit: "Schließen",
            usePos: "Position nehmen [U]",
            reset: "Reset",
            barUndo: "Undo",
            barSave: "Speichern",
            barFlip: "Flip [F]",
            barFlipOn: "Flip AN [F]",
            barCopy: "Kopieren",
            barCut: "Ausschneiden",
            barPaste: "Einfügen",
            barDelete: "Löschen",
            barPlace: "Platz. [␣]",
            trapsTitle: "Fallen",
            lethalTitle: "Tödliche Fallen",
            helpTraps: "Key wählen, Flip/Rot/Sort, Punkt klicken, Platzieren. LMB auf gesetzte Falle = Bearbeiten/Löschen. (?) = nicht im Cache.",
            helpLethal: "Tödliche HellGate-Fallen (Gore). Nur Flip/Sort (keine Rotation). Gore Content nötig.",
            flipOn: "Nach links [F]",
            flipOff: "Nach rechts [F]",
            ready: "Bereit",
            enemiesTitle: "Gegner",
            favTitle: "Favoriten",
            favEmpty: "Leer — Key wählen, dann ★.",
            favAdd: "★ Aktuelles hinzufügen",
            factionTitle: "Fraktion",
            elite: "Elite",
            flip: "Nach links flippen",
            rot: "Drehen",
            degrees: "Grad",
            apply: "OK",
            sort: "Sort",
            random: "Zufallschance",
            options: "Optionen",
            preview: "Vorschau",
            pickEnemy: "Gegner wählen",
            pickTrap: "Falle wählen",
            noPrefab: "Kein Prefab",
            noMesh: "Kein Mesh",
            unavailable: "Nicht verfügbar",
            na: "[N/V]",
            enemyNa: "Dieser Gegner ist fürs Authoring gesperrt.",
            helpTitle: "Hilfe",
            guideTitle: "Steuerung",
            cam: "Kamera / Bewegung",
            camBody: "WASD — Kamera bewegen\nMMB halten und ziehen — Kamera mit der Maus bewegen\nRad — Zoom (Übersicht AN)\nV — Übersicht / Default\nHome — Kamera zum Spieler (Übersicht bleibt, Zoom zurück)",
            mouse: "Maus",
            mouseBody: "LMB auf leeren Boden — Punkt setzen\nLMB-ziehen auf leeren Boden — Rahmen wählen\nLMB auf Sprite — wählen / bearbeiten (genau; Alt = größer)\nLMB auf Objekt halten — verschieben\nPfeile — Auswahl schieben (Shift+Pfeile ×5)\nVorschau oder Liste auf die Karte ziehen — platzieren und speichern\nRMB — Pack speichern und Szene neu laden",
            catalogs: "Kataloge",
            catalogsBody: "E — Gegner\nH — Geiseln\nT — Fallen\nR — Tödliche Fallen\nG — Gold\nN — Deko\nM — EventTrap\nC — EventCore\nB — Favoriten\nF — Spiegeln\nSpace / Enter — Platzieren\nU — Position übernehmen\nQ — Panels (und diese Hilfe) schließen",
            editClip: "Bearbeiten & Zwischenablage",
            editBody: "Ctrl+C — kopieren\nCtrl+X — ausschneiden\nCtrl+V — am Punkt einfügen\nCtrl+D — duplizieren\nCtrl+Z — rückgängig\nCtrl+S — Bearbeitung speichern\nCtrl+B — zu Favoriten\nDel — löschen (ein Rahmen löscht alles darin)\nF12 — Screenshot\nF1 — diese Hilfe\nEsc — Hilfe, dann Rahmen, dann Edit, dann Auswahl schließen",
            footer: "Mit ? auf einem Panel extra Tipps.",
            helpCoords: "LMB auf leeren Boden = Punkt. LMB-ziehen = Rahmen (Ctrl+C/X, Ctrl+V am Punkt). LMB auf Sprite = wählen/bearbeiten (Alt = größer). LMB halten = verschieben. MMB / WASD = Kamera bewegen. Rad = Zoom. Pfeile (Shift+Pfeile ×5). Home = Kamera zum Spieler. F1 Hilfe. F12 Screenshot. − klappt dieses Panel ein.",
            helpFaction: "Fraktion in der Pack-Zeile. Wappen = HellGate-Icon. < > zum Wechseln. Anzeigename nur UI; Pack speichert den Token.",
            helpOpt: "Elite = ForceElite. Flip = −X. Random = RANDOM,chance.",
            helpTrapOpt: "Flip = horizontal. Drehen: +30° [R] oder Grad + OK. Sort = sort±N (SortingOrder, nicht near/far).",
            helpHostOpt: "Flip = horizontal. Sort = sort±N. Random schreibt RANDOM_HOSTAGE. Geiseln und OtherScenes drehen nicht.",
            helpLetOpt: "Flip = horizontal. Sort = sort±N. Tödliche Fallen drehen nicht.",
            helpPrev: "Miniatur des Gegners. Aus Vorschau/Liste auf die Karte ziehen = platzieren & speichern.",
            helpPrevTrap: "Fallen-Vorlage. Ziehen = platzieren & speichern. (?) = zuerst eine Karte mit dieser Falle besuchen.",
            dragPlace: "Aus Vorschau oder Liste auf die Karte ziehen",
            dragRelease: "Loslassen = platzieren & speichern",
            facNone: "Keine",
            facBandits: "Banditen",
            facInq: "Banditen (Inquisition)",
            facMafia: "Banditen (Mafia)",
            facDemons: "Banditen (Dämonen)",
            facChurch: "Kirche",
            facDemons2: "Dämonen",
            facMafia2: "Mafia",
            facUndead: "Untote",
            facMonsters: "Monster",
            facWitch: "Hexe",
            facEvent: "Event-Begegnung",
            editTitle: "Ausgewählt",
            editKey: "Key",
            editFaction: "Fraktion",
            editRandom: "Zufalls-Spawn",
            editChance: "Chance",
            editVanilla: "Nicht mit Pack verknüpft — Bearbeitung nicht möglich.",
            panelsClosed: "Panels geschlossen [Q]",
            pickKey: "Zuerst einen Key wählen.",
            selectEnemy: "Zuerst einen Gegner wählen (Hover + LMB).",
            editDisabled: "Nicht mit Pack verknüpft — Bearbeitung nicht möglich.",
            pasteNeed: "Karte klicken, dann Ctrl+V.",
            camHome: "Kamera → Spieler",
            camHomeFail: "Spieler nicht gefunden.",
            badSort: "Ungültiger Sort-Wert.",
            badRot: "Ungültige Drehgrade.",
            done: "Fertig.",
            noLink: "Nicht mit Pack verknüpft.",
            noLinkXy: "Nicht mit Pack verknüpft — XY nicht geschrieben.",
            keyReq: "Key erforderlich.",
            badXy: "Ungültige X/Y (Format 12.34).",
            goldReq: "Goldmenge erforderlich.",
            delFail: "Löschen fehlgeschlagen.",
            cutFail: "Ausschneiden fehlgeschlagen.",
            copyFail: "Kopieren fehlgeschlagen.",
            pasteFail: "Einfügen fehlgeschlagen.",
            undoEmpty: "Nichts zum Rückgängigmachen.",
            savedXy: "XY ins Pack geschrieben",
            cutCount: "Ausgeschnitten × {0}  → Ctrl+V am Punkt",
            deletedCount: "Gelöscht × {0}  (Ctrl+Z Undo)",
            copyDelFail: "{0}  (Löschen fehlgeschlagen: {1})",
            savedKeyAt: "Gespeichert {0} @ {1},{2} → Zeile {3}",
            selectPack: "Zuerst ein HellGate-Pack-Objekt wählen (Vanilla nicht bearbeitbar).",
            deletedLine: "Pack-Zeile {0}{1} gelöscht  (Ctrl+Z Undo)",
            regionEmpty: "Rahmen leer.",
            delRegionFail: "Rahmen löschen fehlgeschlagen.",
            needPoint: "Zuerst auf die Karte klicken (LMB).",
            noEnemy: "Kein Gegner bestätigt.",
            noTrap: "Keine Falle bestätigt.",
            noGold: "Keine Goldmenge.",
            noFolder: "Kein EventTrap-Ordner.",
            camMissing: "Kamera nicht gefunden.",
            camSize: "Kamera-Basisgröße nicht lesbar.",
            overviewOn: "Übersicht AN — WASD / MMB-ziehen bewegen die Kamera, Rad zoom. V = Default.",
            viewDefault: "Übersicht Default (Standard).");
    }

    private static void ApplyPt(Dictionary<string, string> d)
    {
        ApplyIberian(d, brazilian: false);
    }

    private static void ApplyBr(Dictionary<string, string> d)
    {
        ApplyIberian(d, brazilian: true);
    }

    private static void ApplyEs(Dictionary<string, string> d)
    {
        ApplyEastAsian(d,
            coordsTitle: "Colocación",
            point: "Punto",
            pack: "Pack",
            pending: "Pendiente",
            clipboard: "Copiado",
            selected: "Seleccionado",
            line: "Línea",
            hotkeys: "LMB = Punto · LMB-arrastrar = marco · Ctrl+C/X/V/D · flechas · Shift+flechas · E H T R G N M C F B V U · Home · Space · RMB reload · F12 · F1 · Q",
            dragging: "Arrastrando…",
            clickReady: "Punto de spawn listo",
            clickUpdated: "Coordenadas actualizadas",
            marker: "SPAWN",
            copied: "Objeto copiado",
            cut: "Cortado",
            pasted: "Pegado",
            duplicated: "Duplicado",
            deleted: "Eliminado",
            shotOk: "Captura guardada",
            shotFail: "Fallo al capturar",
            btnShot: "Captura [F12]",
            btnHelp: "Ayuda [F1]",
            enemies: "Enemigos [E]",
            enemiesOpen: "Enemigos ▲ [E]",
            hostage: "Rehén [H]",
            hostageOpen: "Rehén ▲ [H]",
            hostageTitle: "Rehenes & OtherScenes",
            helpHostage: "Rehenes y luego animaciones Spine (Look_Dorei, gob_look, …). |faction= se hereda al combatiente tras el rescate. Random escribe RANDOM_HOSTAGE.",
            trap: "Trampa [T]",
            trapOpen: "Trampa ▲ [T]",
            lethal: "Letal [R]",
            lethalOpen: "Letal ▲ [R]",
            decor: "Decor [N]",
            decorOpen: "Decor ▲ [N]",
            gold: "Oro [G]",
            goldOpen: "Oro ▲ [G]",
            goldTitle: "Montones de oro",
            helpGold: "Coloca un montón de oro. Fijo o rango. Random escribe RANDOM,chance,X,Y,gold=…",
            helpGoldOpt: "Random = RANDOM,chance. Estático = GOLD,X,Y,amount,1.",
            etTitle: "Anclas EventTrap",
            helpEt: "Escribe EVENTTRAP,folder,X,Y más count/dist/sides/faction/max/r/delay opcionales. Vacío = config.json del pack. F11 muestra un gizmo (invisible en juego).",
            helpEtGizmo: "Ancla de emboscada/refuerzo solo del editor. Invisible en el juego. Arrastra o escribe XY, luego Usar posición / Guardar.",
            helpEtOpt: "Vacío = valores del pack. Distancia desde el jugador al knockdown, no desde el ancla. Facción a enemigos de emboscada. Sides: pack / both / right-only.",
            ecNone: "Ninguno",
            ecAttach: "Evento p=",
            helpEc: "Coloca un NPC de diálogo: TouzokuNormal|ec_event=<id>. Broker / FSP bandits siempre TouzokuNormal. Clic en Punto, luego Colocar. LMB en el NPC para editar.",
            helpEcOpt: "Random = probabilidad de aparición del NPC (RANDOM,chance). Evento p= = |ec_chance=. El NPC siempre aparece; 1 = diálogo siempre. Facción por defecto = encuentro de evento.",
            helpPrevEc: "Vista previa del prefab NPC. Arrastra desde la vista o la lista al mapa para colocar y guardar.",
            count: "Cant.",
            dist: "Dist",
            max: "Máx",
            zone: "Zona",
            delay: "Retraso",
            sidesPack: "Lados: pack",
            sidesBoth: "Lados: ambos",
            sidesRight: "Lados: derecha",
            decorTitle: "Decoración",
            spine: "— Animaciones Spine —",
            helpDecor: "Cajas, barriles, cadáveres, props. Looks Spine en Rehenes & OtherScenes. (?) = aún no en caché.",
            fav: "Favoritos ★ [B]",
            favOpen: "Favoritos ▲ [B]",
            btnDel: "Borrar [Del]",
            btnUndo: "Deshacer  [Ctrl+Z]",
            btnCopy: "Copiar [Ctrl+C]",
            btnCut: "Cortar [Ctrl+X]",
            btnPaste: "Pegar [Ctrl+V]",
            viewOff: "Vista [V]",
            viewOn: "Vista ON [V]",
            confirm: "Colocar  [Space]",
            confirmFull: "Colocar y guardar  [Space]",
            addFav: "★ A favoritos [Ctrl+B]",
            favDel: "Bor.",
            btnSave: "Guardar  [Ctrl+S]",
            btnSaved: "✓ Guardado",
            closeEdit: "Cerrar",
            usePos: "Usar posición [U]",
            reset: "Reset",
            barUndo: "Deshacer",
            barSave: "Guardar",
            barFlip: "Flip [F]",
            barFlipOn: "Flip ON [F]",
            barCopy: "Copiar",
            barCut: "Cortar",
            barPaste: "Pegar",
            barDelete: "Borrar",
            barPlace: "Colocar [␣]",
            trapsTitle: "Trampas",
            lethalTitle: "Trampas letales",
            helpTraps: "Elige clave, flip/rot/sort, clic en Punto, Colocar. LMB en trampa colocada = editar/borrar. (?) = no en caché.",
            helpLethal: "Trampas letales HellGate (gore). Solo flip/sort (sin rotación). Requiere Gore Content.",
            flipOn: "Hacia la izquierda [F]",
            flipOff: "Hacia la derecha [F]",
            ready: "Listo",
            enemiesTitle: "Enemigos",
            favTitle: "Favoritos",
            favEmpty: "Vacío — elige una clave y pulsa ★.",
            favAdd: "★ Añadir actual",
            factionTitle: "Facción",
            elite: "Élite",
            flip: "Voltear a la izquierda",
            rot: "Rotar",
            degrees: "Grados",
            apply: "OK",
            sort: "Sort",
            random: "Probabilidad aleatoria",
            options: "Opciones",
            preview: "Vista previa",
            pickEnemy: "Elige un enemigo",
            pickTrap: "Elige una trampa",
            noPrefab: "Sin prefab",
            noMesh: "Sin mesh",
            unavailable: "No disponible",
            na: "[N/D]",
            enemyNa: "Este enemigo no está disponible para editar.",
            helpTitle: "Ayuda",
            guideTitle: "Controles",
            cam: "Cámara / movimiento",
            camBody: "WASD — mover la cámara\nMantén MMB y arrastra — mover la cámara con el ratón\nRueda — zoom (activa Vista)\nV — Vista / Default\nHome — cámara al jugador (Vista se mantiene, el zoom se restablece)",
            mouse: "Ratón",
            mouseBody: "LMB en el suelo vacío — poner el Punto\nLMB-arrastrar en el suelo — seleccionar un marco\nLMB en un sprite — seleccionar / editar (preciso; Alt = más amplio)\nMantén LMB en un objeto — moverlo\nFlechas — desplazar la selección (Shift+flechas ×5)\nArrastra la vista previa o la lista al mapa — colocar y guardar\nRMB — guardar el pack y recargar la escena",
            catalogs: "Catálogos",
            catalogsBody: "E — Enemigos\nH — Rehenes\nT — Trampas\nR — Trampas letales\nG — Oro\nN — Decor\nM — EventTrap\nC — EventCore\nB — Favoritos\nF — Voltear\nSpace / Enter — Colocar\nU — Usar posición\nQ — cerrar paneles (y esta ayuda)",
            editClip: "Edición y portapapeles",
            editBody: "Ctrl+C — copiar\nCtrl+X — cortar\nCtrl+V — pegar en el Punto\nCtrl+D — duplicar\nCtrl+Z — deshacer\nCtrl+S — guardar la edición\nCtrl+B — añadir a favoritos\nDel — borrar (un marco borra todo dentro)\nF12 — captura\nF1 — esta ayuda\nEsc — cerrar ayuda, luego el marco, luego la edición, luego la selección",
            footer: "Pasa el cursor por ? en un panel para más consejos.",
            helpCoords: "LMB en el suelo vacío = Punto. LMB-arrastrar = marco (Ctrl+C/X, Ctrl+V en el Punto). LMB en un sprite = seleccionar/editar (Alt = más amplio). Mantén LMB = mover. MMB / WASD = mover la cámara. Rueda = zoom. Flechas (Shift+flechas ×5). Home = cámara al jugador. F1 ayuda. F12 captura. − pliega este panel.",
            helpFaction: "Facción en la línea del pack. Emblema = icono HellGate. < > para ciclar. Nombres de UI; el pack guarda el token técnico.",
            helpOpt: "Élite = ForceElite. Flip = −X. Random = RANDOM,chance.",
            helpTrapOpt: "Flip = horizontal. Rotación: +30° [R] o grados + OK. Sort = sort±N (SortingOrder, no near/far).",
            helpHostOpt: "Flip = horizontal. Sort = sort±N. Random escribe RANDOM_HOSTAGE. Rehenes y OtherScenes no rotan.",
            helpLetOpt: "Flip = horizontal. Sort = sort±N. Las trampas letales no rotan.",
            helpPrev: "Miniatura del enemigo. Arrastra vista/lista al mapa para colocar y guardar.",
            helpPrevTrap: "Plantilla de trampa. Arrastra para colocar y guardar. (?) = visita primero un mapa con esa trampa.",
            dragPlace: "Arrastra la vista o la lista al mapa",
            dragRelease: "Suelta para colocar y guardar",
            facNone: "Ninguna",
            facBandits: "Bandidos",
            facInq: "Bandidos (Inquisición)",
            facMafia: "Bandidos (Mafia)",
            facDemons: "Bandidos (Demonios)",
            facChurch: "Iglesia",
            facDemons2: "Demonios",
            facMafia2: "Mafia",
            facUndead: "No muertos",
            facMonsters: "Monstruos",
            facWitch: "Bruja",
            facEvent: "Encuentro de evento",
            editTitle: "Seleccionado",
            editKey: "Clave",
            editFaction: "Facción",
            editRandom: "Spawn aleatorio",
            editChance: "Probabilidad",
            editVanilla: "Sin vínculo al pack — no se puede editar.",
            panelsClosed: "Paneles cerrados [Q]",
            pickKey: "Elige primero una clave.",
            selectEnemy: "Selecciona primero un enemigo (hover + LMB).",
            editDisabled: "Sin vínculo al pack — no se puede editar.",
            pasteNeed: "Haz clic en el mapa y luego Ctrl+V.",
            camHome: "Cámara → jugador",
            camHomeFail: "Jugador no encontrado.",
            badSort: "Sort inválido.",
            badRot: "Grados de rotación inválidos.",
            done: "Hecho.",
            noLink: "Sin vínculo al pack.",
            noLinkXy: "Sin vínculo al pack — XY no escritos.",
            keyReq: "Se requiere clave.",
            badXy: "X/Y inválidos (formato 12.34).",
            goldReq: "Se requiere cantidad de oro.",
            delFail: "Error al borrar.",
            cutFail: "Error al cortar.",
            copyFail: "Error al copiar.",
            pasteFail: "Error al pegar.",
            undoEmpty: "Nada que deshacer.",
            savedXy: "XY guardados → pack",
            cutCount: "Cortado × {0}  → Ctrl+V en el Punto",
            deletedCount: "Eliminado × {0}  (Ctrl+Z deshacer)",
            copyDelFail: "{0}  (falló el borrado: {1})",
            savedKeyAt: "Guardado {0} @ {1},{2} → línea {3}",
            selectPack: "Selecciona primero un spawn HellGate (vanilla no se edita/borra).",
            deletedLine: "Línea de pack {0}{1} eliminada  (Ctrl+Z deshacer)",
            regionEmpty: "Marco vacío.",
            delRegionFail: "Error al borrar el marco.",
            needPoint: "Haz clic primero en el mapa (LMB).",
            noEnemy: "Ningún enemigo confirmado.",
            noTrap: "Ninguna trampa confirmada.",
            noGold: "Sin cantidad de oro.",
            noFolder: "Sin carpeta EventTrap.",
            camMissing: "Cámara no encontrada.",
            camSize: "No se pudo leer el tamaño base de la cámara.",
            overviewOn: "Vista ON — WASD / MMB-arrastrar mueven la cámara, rueda zoom. V = Default.",
            viewDefault: "Vista Default (estándar).");
    }

    private static void ApplyIberian(Dictionary<string, string> d, bool brazilian)
    {
        ApplyEastAsian(d,
            coordsTitle: "Colocação",
            point: "Ponto",
            pack: "Pack",
            pending: "Pendente",
            clipboard: "Copiado",
            selected: "Selecionado",
            line: "Linha",
            hotkeys: "LMB = Ponto · LMB-arrastar = caixa · Ctrl+C/X/V/D · setas · Shift+setas · E H T R G N M C F B V U · Home · Space · RMB reload · F12 · F1 · Q",
            dragging: "A arrastar…",
            clickReady: "Ponto de spawn pronto",
            clickUpdated: "Coordenadas atualizadas",
            marker: "SPAWN",
            copied: "Objeto copiado",
            cut: "Cortado",
            pasted: "Colado",
            duplicated: "Duplicado",
            deleted: "Apagado",
            shotOk: "Captura guardada",
            shotFail: "Falha na captura",
            btnShot: "Captura [F12]",
            btnHelp: "Ajuda [F1]",
            enemies: "Inimigos [E]",
            enemiesOpen: "Inimigos ▲ [E]",
            hostage: "Refém [H]",
            hostageOpen: "Refém ▲ [H]",
            hostageTitle: "Reféns & OtherScenes",
            helpHostage: "Reféns e depois animações Spine (Look_Dorei, gob_look, …). |faction= passa para o combatente após o resgate. Random escreve RANDOM_HOSTAGE.",
            trap: "Armadilha [T]",
            trapOpen: "Armadilha ▲ [T]",
            lethal: "Letal [R]",
            lethalOpen: "Letal ▲ [R]",
            decor: "Decor [N]",
            decorOpen: "Decor ▲ [N]",
            gold: "Ouro [G]",
            goldOpen: "Ouro ▲ [G]",
            goldTitle: "Pilhas de ouro",
            helpGold: "Coloca uma pilha de ouro. Fixo ou intervalo. Random escreve RANDOM,chance,X,Y,gold=…",
            helpGoldOpt: "Random = RANDOM,chance. Estático = GOLD,X,Y,amount,1.",
            etTitle: "Âncoras EventTrap",
            helpEt: "Escreve EVENTTRAP,folder,X,Y mais count/dist/sides/faction/max/r/delay opcionais. Vazio = config.json do pack. F11 mostra um gizmo (invisível no jogo).",
            helpEtGizmo: "Âncora de emboscada/reforço só do editor. Invisível no jogo. Arrasta ou escreve XY, depois Usar posição / Guardar.",
            helpEtOpt: "Vazio = defaults do pack. Distância a partir do jogador no knockdown, não da âncora. Facção nos inimigos da emboscada. Sides: pack / both / right-only.",
            ecNone: "Nenhum",
            ecAttach: "Evento p=",
            helpEc: "Coloca um NPC de diálogo: TouzokuNormal|ec_event=<id>. Broker / FSP bandits sempre TouzokuNormal. Clica Ponto, depois Colocar. LMB no NPC para editar.",
            helpEcOpt: "Random = chance de aparecer o NPC (RANDOM,chance). Evento p= = |ec_chance=. O NPC sempre spawna; 1 = diálogo sempre. Facção padrão = encontro de evento.",
            helpPrevEc: "Pré-visualização do prefab NPC. Arrasta da pré-visualização ou lista para o mapa para colocar e guardar.",
            count: "Qtd",
            dist: "Dist",
            max: "Máx",
            zone: "Zona",
            delay: "Atraso",
            sidesPack: "Lados: pack",
            sidesBoth: "Lados: ambos",
            sidesRight: "Lados: direita",
            decorTitle: "Decoração",
            spine: "— Animações Spine —",
            helpDecor: "Caixas, barris, cadáveres, props. Looks Spine em Reféns & OtherScenes. (?) = ainda não está em cache.",
            fav: "Favoritos ★ [B]",
            favOpen: "Favoritos ▲ [B]",
            btnDel: "Apagar [Del]",
            btnUndo: "Desfazer  [Ctrl+Z]",
            btnCopy: "Copiar [Ctrl+C]",
            btnCut: "Cortar [Ctrl+X]",
            btnPaste: "Colar [Ctrl+V]",
            viewOff: "Vista [V]",
            viewOn: "Vista ON [V]",
            confirm: "Colocar  [Space]",
            confirmFull: "Colocar e guardar  [Space]",
            addFav: "★ Nos favoritos [Ctrl+B]",
            favDel: "Apag.",
            btnSave: "Guardar  [Ctrl+S]",
            btnSaved: "✓ Guardado",
            closeEdit: "Fechar",
            usePos: "Usar posição [U]",
            reset: "Reset",
            barUndo: "Desfazer",
            barSave: "Guardar",
            barFlip: "Flip [F]",
            barFlipOn: "Flip ON [F]",
            barCopy: "Copiar",
            barCut: "Cortar",
            barPaste: "Colar",
            barDelete: "Apagar",
            barPlace: "Colocar [␣]",
            trapsTitle: "Armadilhas",
            lethalTitle: "Armadilhas letais",
            helpTraps: "Escolhe a chave, flip/rot/sort, clica Ponto, Colocar. LMB numa armadilha colocada = editar/apagar. (?) = sem cache.",
            helpLethal: "Armadilhas letais HellGate (gore). Só flip/sort (sem rotação). Precisa de Gore Content.",
            flipOn: "Para a esquerda [F]",
            flipOff: "Para a direita [F]",
            ready: "Pronto",
            enemiesTitle: "Inimigos",
            favTitle: "Favoritos",
            favEmpty: "Vazio — escolhe uma chave e ★.",
            favAdd: "★ Adicionar atual",
            factionTitle: "Facção",
            elite: "Elite",
            flip: "Virar à esquerda",
            rot: "Rodar",
            degrees: "Graus",
            apply: "OK",
            sort: "Sort",
            random: "Chance aleatória",
            options: "Opções",
            preview: "Pré-visualização",
            pickEnemy: "Escolhe um inimigo",
            pickTrap: "Escolhe uma armadilha",
            noPrefab: "Sem prefab",
            noMesh: "Sem mesh",
            unavailable: "Indisponível",
            na: "[N/D]",
            enemyNa: "Este inimigo não está disponível para edição.",
            helpTitle: "Ajuda",
            guideTitle: "Controlos",
            cam: "Câmara / movimento",
            camBody: "WASD — mover a câmara\nSegura MMB e arrasta — mover a câmara com o rato\nRoda — zoom (liga a Vista)\nV — Vista / Default\nHome — câmara no jogador (a Vista mantém-se, o zoom volta atrás)",
            mouse: "Rato",
            mouseBody: "LMB no chão vazio — pôr o Ponto\nLMB-arrastar no chão — selecionar uma caixa\nLMB num sprite — selecionar / editar (preciso; Alt = mais largo)\nSegura LMB num objeto — movê-lo\nSetas — deslocar a seleção (Shift+setas ×5)\nArrasta a pré-visualização ou a lista para o mapa — colocar e guardar\nRMB — guardar o pack e recarregar a cena",
            catalogs: "Catálogos",
            catalogsBody: "E — Inimigos\nH — Reféns\nT — Armadilhas\nR — Armadilhas letais\nG — Ouro\nN — Decor\nM — EventTrap\nC — EventCore\nB — Favoritos\nF — Inverter\nSpace / Enter — Colocar\nU — Usar posição\nQ — fechar painéis (e esta ajuda)",
            editClip: "Edição e área de transferência",
            editBody: "Ctrl+C — copiar\nCtrl+X — cortar\nCtrl+V — colar no Ponto\nCtrl+D — duplicar\nCtrl+Z — anular\nCtrl+S — guardar a edição\nCtrl+B — adicionar aos favoritos\nDel — apagar (uma caixa apaga tudo dentro)\nF12 — captura\nF1 — esta ajuda\nEsc — fechar a ajuda, depois a caixa, depois a edição, depois a seleção",
            footer: "Pousa em ? num painel para mais dicas.",
            helpCoords: "LMB no chão vazio = Ponto. LMB-arrastar no chão = caixa (Ctrl+C/X, Ctrl+V no Ponto). LMB num sprite = selecionar/editar (Alt = mais largo). Segura LMB = mover. MMB / WASD = mover a câmara. Roda = zoom. Setas (Shift+setas ×5). Home = câmara no jogador. F1 ajuda. F12 captura. − dobra este painel.",
            helpFaction: "Facção na linha do pack. Emblema = ícone HellGate. < > para circular. Nomes só de UI; o pack guarda o token técnico.",
            helpOpt: "Elite = ForceElite. Flip = −X. Random = RANDOM,chance.",
            helpTrapOpt: "Flip = horizontal. Rotação: +30° [R] ou graus + OK. Sort = sort±N (SortingOrder, não near/far).",
            helpHostOpt: "Flip = horizontal. Sort = sort±N. Random escreve RANDOM_HOSTAGE. Reféns e OtherScenes não rodam.",
            helpLetOpt: "Flip = horizontal. Sort = sort±N. Armadilhas letais não rodam.",
            helpPrev: "Miniatura do inimigo. Arrasta pré-visualização/lista para o mapa para colocar e guardar.",
            helpPrevTrap: "Modelo de armadilha. Arrasta para colocar e guardar. (?) = visita primeiro um mapa com essa armadilha.",
            dragPlace: "Arrasta a pré-visualização ou a lista para o mapa",
            dragRelease: "Larga para colocar e guardar",
            facNone: "Nenhuma",
            facBandits: "Bandidos",
            facInq: "Bandidos (Inquisição)",
            facMafia: "Bandidos (Máfia)",
            facDemons: "Bandidos (Demónios)",
            facChurch: "Igreja",
            facDemons2: brazilian ? "Demônios" : "Demónios",
            facMafia2: brazilian ? "Máfia" : "Máfia",
            facUndead: "Mortos-vivos",
            facMonsters: "Monstros",
            facWitch: brazilian ? "Bruxa" : "Bruxa",
            facEvent: "Encontro de evento",
            editTitle: "Selecionado",
            editKey: "Chave",
            editFaction: "Facção",
            editRandom: "Spawn aleatório",
            editChance: "Chance",
            editVanilla: "Sem ligação ao pack — edição indisponível.",
            panelsClosed: "Painéis fechados [Q]",
            pickKey: "Escolhe primeiro uma chave.",
            selectEnemy: "Seleciona primeiro um inimigo (hover + LMB).",
            editDisabled: "Sem ligação ao pack — edição indisponível.",
            pasteNeed: "Clica no mapa e depois Ctrl+V.",
            camHome: "Câmara → jogador",
            camHomeFail: "Jogador não encontrado.",
            badSort: "Sort inválido.",
            badRot: "Graus de rotação inválidos.",
            done: "Feito.",
            noLink: "Sem ligação ao pack.",
            noLinkXy: "Sem ligação ao pack — XY não escritos.",
            keyReq: "Chave necessária.",
            badXy: "X/Y inválidos (formato 12.34).",
            goldReq: "Quantidade de ouro necessária.",
            delFail: "Falha ao apagar.",
            cutFail: "Falha ao cortar.",
            copyFail: "Falha ao copiar.",
            pasteFail: "Falha ao colar.",
            undoEmpty: "Nada a desfazer.",
            savedXy: "XY guardados → pack",
            cutCount: "Cortado × {0}  → Ctrl+V no Ponto",
            deletedCount: "Apagado × {0}  (Ctrl+Z desfazer)",
            copyDelFail: "{0}  (falhou apagar: {1})",
            savedKeyAt: "Guardado {0} @ {1},{2} → linha {3}",
            selectPack: "Seleciona primeiro um spawn HellGate (vanilla não se edita/apaga).",
            deletedLine: "Linha de pack {0}{1} apagada  (Ctrl+Z desfazer)",
            regionEmpty: "Caixa vazia.",
            delRegionFail: "Falha ao apagar a caixa.",
            needPoint: "Clica primeiro no mapa (LMB).",
            noEnemy: "Nenhum inimigo confirmado.",
            noTrap: "Nenhuma armadilha confirmada.",
            noGold: "Sem quantidade de ouro.",
            noFolder: "Sem pasta EventTrap.",
            camMissing: "Câmara não encontrada.",
            camSize: "Não foi possível ler o tamanho base da câmara.",
            overviewOn: "Vista ON — WASD / MMB-arrastar movem a câmara, roda zoom. V = Default.",
            viewDefault: "Vista Default (padrão).");
        if (brazilian)
        {
            d["help.guide.camera"] = "Câmera / movimento";
            d["status.cameraHome"] = "Câmera → jogador";
            d["status.cameraMissing"] = "Câmera não encontrada.";
            d["status.cameraSizeFail"] = "Não foi possível ler o tamanho base da câmera.";
            d["help.guide.mouse"] = "Mouse";
            d["btn.save"] = "Salvar  [Ctrl+S]";
            d["btn.saved"] = "✓ Salvo";
            d["bar.save"] = "Salvar";
            d["btn.confirmFull"] = "Colocar e salvar  [Space]";
            d["preview.dragRelease"] = "Solta para colocar e salvar";
            d["status.savedXy"] = "XY salvos → pack";
            d["status.savedKeyAt"] = "Salvo {0} @ {1},{2} → linha {3}";
            d["status.dragging"] = "Arrastando…";
            d["btn.screenshot"] = "Print [F12]";
            d["help.guide.camera.body"] =
                "WASD — mover a câmera\nSegura MMB e arrasta — mover a câmera com o mouse\nRoda — zoom (liga a Vista)\nV — Vista / Default\nHome — câmera no jogador (a Vista continua, o zoom volta)";
            d["help.guide.mouse.body"] =
                "LMB no chão vazio — pôr o Ponto\nLMB-arrastar no chão — selecionar uma caixa\nLMB num sprite — selecionar / editar (preciso; Alt = mais largo)\nSegura LMB num objeto — movê-lo\nSetas — deslocar a seleção (Shift+setas ×5)\nArrasta a pré-visualização ou a lista para o mapa — colocar e salvar\nRMB — salvar o pack e recarregar a cena";
            d["help.guide.edit.body"] =
                "Ctrl+C — copiar\nCtrl+X — cortar\nCtrl+V — colar no Ponto\nCtrl+D — duplicar\nCtrl+Z — desfazer\nCtrl+S — salvar a edição\nCtrl+B — adicionar aos favoritos\nDel — apagar (uma caixa apaga tudo dentro)\nF12 — captura\nF1 — esta ajuda\nEsc — fechar a ajuda, depois a caixa, depois a edição, depois a seleção";
            d["help.coords"] =
                "LMB no chão vazio = Ponto. LMB-arrastar no chão = caixa (Ctrl+C/X, Ctrl+V no Ponto). LMB num sprite = selecionar/editar (Alt = mais largo). Segura LMB = mover. MMB / WASD = mover a câmera. Roda = zoom. Setas (Shift+setas ×5). Home = câmera no jogador. F1 ajuda. F12 captura. − dobra este painel.";
            d["status.overviewOn"] =
                "Vista ON — WASD / MMB-arrastar movem a câmera, roda zoom. V = Default.";
        }
        else
        {
            d["help.guide.camera"] = "Câmara / movimento";
        }
    }
}
